server:
  port: 80

eureka:
  instance:
    hostname: zira-eureka
  client:
    registerWithEureka: false
    fetchRegistry: false
#    healthcheck:
#      enabled: true
    serviceUrl:
      defaultZone: http://zira-eureka/eureka
#    enabled: true

spring:
  application:
    name: zira-eureka
  profiles:
    active: dev
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: ["health","beans","env","prometheus","info","metrics"]
#      base-path: /
#  #      enabled-by-default: true
#  endpoint:
#    auditevents:
#      enabled: true
#      cache:
#        time-to-live: 10s
#    beans:
#      enabled: true
#    conditions:
#      enabled: true
#    configprops:
#      enabled: true
#    prometheus:
#      enabled: true
#  metrics:
#    tags:
#      application:
#        ${spring:application:name}
#    export:
#      prometheus:
#        pushgateway:
#          base-url: 101.132.169.36:9091
#          enabled: true